server.port=8080
server.servlet.context-path=/lib
logging.level.org.springframework=debug
## ??mapper??????
logging.level.com.highcom.demo.mapper=debug

spring.datasource.username=root
spring.datasource.password=747603
spring.datasource.url=jdbc:mysql://localhost:3306/java126?characterEncoding=utf-8
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

## ??mapper??????
mybatis.mapper-locations=classpath:mapper/*.xml
## ????????????????
mybatis.type-aliases-package=com.hrbsfdx.library_back.pojo